name: Feature request
description: Suggest an idea for Koklo Community
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: What should be added?
    validations:
      required: true
